services:
  mysql: 
    env_file:
      - ./.env
    container_name: mysql
    image: mysql:latest
    expose:
      - '3306'
    networks:
      - base_network
    volumes:
      - db_data:/var/lib/mysql
    
  api: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    image: projetotrainee
    ports:
      - '3030:3030'
    networks:
      - base_network
    volumes:
      - .:/api
    command: npm start
    env_file:
      - ./.env
    depends_on:
      - mysql

networks:
  base_network:
    driver: bridge

volumes:
  db_data:
